spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      default_schema: techapplogistic
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  application:
    name: techpeople
  datasource2:
    driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://201.230.52.56:6023/postgres
    username: postgres
    password: Techpeople@com@1268
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://201.230.52.56:6023/postgres
    username: postgres
    password: Techpeople@com@1268 
  datasource3:
    url: jdbc:h2:mem:testdb
    driverClassName : org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:pool:postgresql://201.230.52.56:6023/postgres
    username: postgres
    password: Techpeople@com@1268
    pool.initial-size: 100
    pool.max-size: 500
    pool.max-idle-time: 30m
    pool.validation-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 3072KB
      max-request-size: 3072KB
app:
  security:
    jwt-signing-key: 123dsdfdf23123

logging:
  level:
    pe.com.targethr: DEBUG
    #org.hibernate: DEBUG