spring:
  application:
    name: techpeople

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.101:1521:TECHDB
    username: TECHAPP
    password: TECHAPP
  servlet:
    multipart:
      max-file-size: 3072KB
      max-request-size: 3072KB
app:
  security:
    browser-client-name: browser_client_teach
    browser-client-secret: teach_people2019
    jwt:
      access-token-duration: 7200
      refresh-token-duration: 86400
      signing-key: 123dsdfdf23123

logging:
  level:
    pe.com.targethr: INFO
    #org.hibernate: DEBUG