spring:
  application:
    name: techpeople
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1 #r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1 #r2dbc:h2:mem:///test #r2dbc:h2:mem:///testdb
    #url: r2dbc:h2:~///test;DB_CLOSE_DELAY=-1 #r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1 #r2dbc:h2:mem:///test #r2dbc:h2:mem:///testdb
    
    driver-class-name: io.r2dbc.h2.H2ConnectionConfiguration #org.h2.Driver
    #driver-class-name: org.h2.Driver
    username: sa
    password: Techpeople@2307
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
    database:
       name: test
       schema: classpath:schema.sql # Ruta opcional al archivo de esquema SQL
app:
  security:
    jwt-signing-key: 123dsdfdf23123

logging:
  level:
    pe.com.techpeople.logistic: DEBUG
    #org.hibernate: DEBUG