spring:
  application:
    name: techpeople
  datasource:
    #url: jdbc:h2:file:/data/demo 
    url: jdbc:h2:~/test
    username: sa
    password: Techpeople@2307
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
      
app:
  security:
    jwt-signing-key: 123dsdfdf23123

logging:
  level:
    org.hibernate: DEBUG